"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicantRouter = void 0;
const express_1 = __importDefault(require("express"));
const Register_1 = require("../../../controller/users/auth/Register");
const Login_1 = require("../../../controller/users/auth/Login");
const GetApplicantDetails_1 = require("../../../controller/users/applicantDetails/GetApplicantDetails");
const applicantQualification_controller_1 = require("../../../controller/users/applicantQualification/applicantQualification.controller");
const applicantSkill_controller_1 = require("../../../controller/users/applicantSkill/applicantSkill.controller");
const GetInvitedJobList_Controller_1 = require("../../../controller/users/applicantInvitedJobLisit/GetInvitedJobList.Controller");
const UpdateApplicantProfileDetails_1 = require("../../../controller/users/applicantDetails/UpdateApplicantProfileDetails");
const ApplicantPrivacy_1 = require("../../../controller/users/applicantPrivacy/ApplicantPrivacy");
const ApplicantApplyJob_1 = require("../../../controller/users/applicantAppliedJobList/ApplicantApplyJob");
const router = express_1.default.Router();
exports.ApplicantRouter = router;
router.get("/applicant/getApplicantDetailsById/:id", GetApplicantDetails_1.getApplicantDetailsById);
router.get("/applicant/getApplicantInvitedJobDetailsList/:id", GetInvitedJobList_Controller_1.getApplicantInvitedJobList);
router.get("/applicant/getApplicantProfilePrivacy/:id", ApplicantPrivacy_1.getApplicantProfilePrivacy);
router.get("/applicant/getApplicantResumePrivacy/:id", ApplicantPrivacy_1.getApplicantResumePrivacy);
router.post("/applicant/register", Register_1.registerNewUser);
router.post("/applicant/login", Login_1.loginUser);
router.post("/applicant/applyJob/:jobId/:applicantId", ApplicantApplyJob_1.applicantApplyJob);
router.put("/applicant/updateApplicantEducation/:id", applicantQualification_controller_1.updateQualification);
router.put("/applicant/updateApplicantSkills/:id/:skill", applicantSkill_controller_1.updateApplicantSkillById);
router.patch("/applicant/updateApplicantProfile/:id", UpdateApplicantProfileDetails_1.updateApplicntProfileDetails);
router.patch("/applicant/updateApplicantPrivacy/:id", ApplicantPrivacy_1.updateApplicantPrivacy);
