export interface JobDetailsPros{
	jobRole:string;
	role:string
	functionalArea:string;
	stateCity:string;
	ctc:number;
	experience:string
	minQualification:string
	openings:number;
	prefExperience:string;
	prefEducation:string;
	jobType:string;
	jobDescription:string;
	companyName:string;
	compnayAbout:string;
	companyIndustry:string;
	companyEstd:string;
	companyEmpCount:number;
	companyWebsite:string;
	companyLinkedIn:string;
}